### ISSUE TITLE
Can't use an undefined value as a HASH reference

### ISSUE THREAD

**Issue by paly2** [gryphonshafer/Bot-IRC-X-Feeds#1]
Hello, sorry for my bad English,
Each time I run the Yet-Another-IRC-Bot with this plugin, I get the error:
```
Can't use an undefined value as a HASH reference at /usr/local/share/perl/5.20.2/Bot/IRC/X/Feeds.pm line 85.
```
Could you give me any help?
Thanks in advance

**Comment by gryphonshafer** [comment]
This is caused by an oversight in Bot::IRC. If a plugin expects some variable to exist in a "vars" definition, but the entire plugin has no "vars" definition (not just missing key/values, but the whole hashref isn't defined), then this error gets thrown. That shouldn't be the case. Instead, Bot::IRC should just silently continue and let the plugin throw an error if a variable is required.

I've just patched Bot::IRC to resolve this. It should show up on CPAN as v1.15 after a little while.

**Comment by paly2** [comment]
Okay, thanks!
